covid/urls.py
from django.urls import path
from .views import side_bar_data, map_bar_data


app_name='covid'
urlpatterns = [
    path('covid19', side_bar_data, name="dashboard" ),
    path('selectCountry',  map_bar_data, name="graphs" ),
]

culture/urls.py
from django.urls import path
from .views import CultureListView, CultureDetailView, CultureCreateView, UpdateCultureView, DeleteCultureView

app_name='culture'
urlpatterns = [
    path('', CultureListView, name='culture_home'),
    path('create/', CultureCreateView.as_view(), name='create_culture'),
    path('<str:slug>/', CultureDetailView.as_view(), name='culture_detail'),
    path('<str:slug>/update', UpdateCultureView.as_view(), name='update_culture'),
    path('<str:slug>/delete', DeleteCultureView.as_view(), name='delete_culture'),


]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView, UpdateProjectView, DeleteProjectView

app_name='projectss'
urlpatterns = [
    path('', ProjectListView, name='project_home'),
    path('create/', ProjectCreateView.as_view(), name='create_project'),
    path('<str:slug>/', ProjectDetailView.as_view(), name='project_detail'),
    path('<str:slug>/update', UpdateProjectView.as_view(), name='update_project'),
    path('<str:slug>/delete', DeleteProjectView.as_view(), name='delete_project'),


]

umoja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('advert/', include('advertisements.urls')),
    path('projects/', include('projects.urls')),
    path('home/', include('updates.urls')),
    path('culture/', include('culture.urls')),
    path('facilities/', include('facilities.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('covid.urls')),
    path('', include('user_auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

updates/urls.py
from django.urls import path
from .views import DisplayNews, NewsDetails , CreateNews, UpdateNews, DeleteNews, homepage

app_name='updates'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('news/', DisplayNews, name='news_list'),
    path('create/', CreateNews.as_view(), name='news_create'),
    path('<str:slug>/', NewsDetails.as_view(), name='news_details'),
    path('<str:slug>/Update', UpdateNews.as_view(), name='news_update'),
    path('<str:slug>/Delete', DeleteNews.as_view(), name='news_delete'),
]

user_auth/urls.py
from django.urls import path
from .views import LoginView,RegisterView
from django.contrib.auth.views import LogoutView

app_name='auth_user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page ='auth_user:login'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

vacancies/urls.py
from django.urls import path
from .views import HouseListView,HouseDetailView, HouseCreate,HouseUpdateForm,HouseDeleteView

app_name='vacancies'
urlpatterns = [
    path('', HouseListView, name='vacancy_home'),
    path('create/', HouseCreate.as_view(), name='vacancy_create'),
    path('<str:slug>/', HouseDetailView.as_view(), name='vacancy_detail'),
    path('<str:slug>/delete', HouseDeleteView.as_view(), name='vacancy_delete'),
    path('<str:slug>/update', HouseUpdateForm.as_view(), name='vacancy_update'),
]

updates/models.py
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

from django.db import models


class Tags(models.Model):
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name

class Updates(models.Model):
    news_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    news_img = models.ImageField(upload_to="images",default='testimon1.jpg.jpg')
    body = RichTextUploadingField()
    slug = models.SlugField(max_length=15, null=True,blank=True)
    important = models.BooleanField(default=False)
    Tags = models.ManyToManyField(Tags, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering: ['-date_created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.title}{self.news_id}')
        super().save(*args, **kwargs)

updates/forms.py
from django import forms
from .models import Updates
from django.forms import ModelForm

class NewsCreateForm(ModelForm):

    class Meta:
        model = Updates
        fields = '__all__'

        widgets={
            'Tags':forms.CheckboxSelectMultiple()
        }

updates/views.py
from django.shortcuts import render
from django.views.generic import CreateView,UpdateView,DetailView,DeleteView,ListView,View
from .models import Updates
from django.urls import reverse_lazy
from .forms import NewsCreateForm
from advertisements.models import Advertisements
from projects.models import Projects
from vacancies.models import Houses
from culture.models import Culture
from facilities.models import Facilities
from .myFilter import UpdateFilter
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.mixins import LoginRequiredMixin



def homepage(request):
    advertisements = Advertisements.objects.filter(home_advert=True)[0:8]
    updates = Updates.objects.filter(important=True).order_by('-date_created')[0:3]
    projects = Projects.objects.all().order_by('-date_published')[0:3]
    vacancies = Houses.objects.all().order_by('-date_created')[0:3]
    culture = Culture.objects.all().order_by('-date_created')[0:3]
    facilities = Facilities.objects.all().order_by('-date_created')[0:3]
    context = {
        'facilities':facilities,
        'culture':culture,
        'vacancies':vacancies,
        'projects':projects,
        'advertisements':advertisements,
        'updates':updates
    }
    return render(request, 'updates/home_page_two.html', context)


def DisplayNews(request):
    advertisements = Advertisements.objects.filter(news_advert=True)[0:8]
    updates = Updates.objects.all().order_by('-date_created')
    myFilter = UpdateFilter(request.GET, queryset=updates)
    updates = myFilter.qs
    page = request.GET.get('page')
    paginator = Paginator(updates, 5)
    try:
        updates = paginator.page(page)
    except PageNotAnInteger:
        updates = paginator.page(1)
    except EmptyPage:
        updates = paginator.page(paginator.num_pages)


    context = {
        'updates': updates,
        'myFilter':myFilter,
        'advertisements': advertisements,
    }
    return render(request, 'updates/news_show.html', context)


class NewsDetails(LoginRequiredMixin,DetailView):
    model = Updates
    context_object_name = 'update'
    template_name = 'updates/detail_news.html'

class CreateNews(CreateView):
    form_class = NewsCreateForm
    template_name = 'updates/news_create.html'
    success_url = reverse_lazy('updates:homepage')

class UpdateNews(UpdateView):
    model = Updates
    fields = '__all__'
    template_name = 'updates/new_update.html'
    success_url = reverse_lazy('updates:homepage')

class DeleteNews(DeleteView):
    model = Updates
    template_name = 'updates/delete_news.html'
    success_url = reverse_lazy('updates:homepage')

updates/templates/updates/delete_news.html
{% extends "index.html" %}
{% block content %}



<div class="create-news" style="margin-top: 2.5%;">
<h1>Are you sure you want to delete this update?</h1>
<form method="post">
    {% csrf_token %}
    <input class="buttonlink" type="submit" value="Confirm">
</form>
</div>
{% endblock %}

updates/templates/updates/detail_news.html
{% extends "index.html" %}
{% block content %}

<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pl-2 pt-0 pb-0 bg-white position-relative">
		<div class="h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">
					<p class="text-uppercase font-weight-bold">
						<a class="text-danger" href="{% url 'updates:news_list' %}">Stories</a>
					</p>
					<h1 class="display-4 secondfont mb-3 font-weight-bold">{{ update.title }}</h1>
					<p class="mb-3">
                        {{ update.description }}
                    </p>
					<div class="d-flex align-items-center">
						<img class="rounded-circle" src="{{ update.news_img.url }}" width="70" height="70">
						<small class="ml-2"> <span class="text-muted d-block">{{ update.date_created }}</span>
							{% if request.user.is_authenticated %}
							<span><a  href="{% url 'updates:news_update' slug=object.slug %}">Update</a>
    						<a class="text-danger" href="{% url 'updates:news_delete' slug=object.slug %}">Delete</a></span>
							{% endif %}
						</small>
					</div>
				</div>
				<div class="col-md-6 pr-0">
					<img width="500" height="300" src="{{ update.news_img.url }}">
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container pt-4 pb-4">
	<div class="row justify-content-center">
		<div class="col-lg-2 pr-4 mb-4 col-md-12">
			<div class="sticky-top text-center">
				<div class="text-muted">
					Share this
				</div>
			</div>
		</div>
		<div class="col-md-12 col-lg-8">
			<article class="article-post">
			<p>
                {{ update.body|safe }}
			</p>
			</article>
			<div class="border p-5 bg-lightblue">
				<div class="row justify-content-between">
					<div class="col-md-5 mb-2 mb-md-0">
						<h5 class="font-weight-bold secondfont">Become a member</h5>
						 Get the latest news right in your inbox. We never spam!
					</div>
					<div class="col-md-7">
						<div class="row">
							<div class="col-md-12">
								<input type="text" class="form-control" placeholder="Enter your e-mail address">
							</div>
							<div class="col-md-12 mt-2">
								<button type="submit" class="btn btn-success btn-block">Subscribe</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="cov-container" style="margin-top: 3%;">
    <div class="covid-container">
        <h4><i>Stay safe.Protect Yourself</i></h4>
        <h4>Mask on,sanitize & wash hands</h4>
        <h6>Check out <a href="{% url 'covid:dashboard' %}" class="covid-butt">Covid19</a> data</h6>
    </div>
</div>







{% endblock %}

updates/templates/updates/home_page.html
{% extends "index.html" %}
{% block content %}
{% load static %}


<style>

 .carousel-item{
 height:32rem;
 background: #7777;
 position: relative;
 }
 .carousel-item img{
 height: 100%;
 width: 100%;
 object-fit:cover;
 }

#section{
background: #000;
}

@media(max-width: 760px){
.news{
font-size: 10px;
flex-basis: 21%;
margin: auto;
}
.news-linkkk{font-size: 12px;}
}

.covid-container{
width: 70%;
margin: auto;
padding: 40px 40px;
text-align: center;
color: #fff;
}
.covid-container{
background-image: url({% static 'images/corona.gif' %})
}
.covid-container h6{
font-size: 10px;
text-align: right;
padding-right: 35%;
}

.covid-butt{
border: 1px solid transparent;
background-color: crimson;
padding:3px 20px;
font-size: 10px;
color: black;
transition: 0.3s ease in;
cursor: pointer;
}
.covid-butt:hover{
background-color: red;
text-decoration: none;
letter-spacing: 1.5px;
color: #fff;
}

.img-wahesh{
height : 240px;
width : 240px;
border: 3px solid #16e0bd;
}

.head-lead{
padding : 10px;
}

@media(max-width: 600px){
.cov-container{
margin-top: 5%;
}
.covid-container h4{
font-size: 15px;
}
.covid-container h6{
padding: 10px 20px;
}
}
</style>

<p class="text-kuwangora">
        <span style="color:blue;font-weight: bold;">S</span>
        <span style="color:yellow;font-weight: bold;">W</span>
        <span style="color:green;font-weight: bold;">A</span>
        <span style="color:red;font-weight: bold;">G</span>
        <span>-</span>
        <span style="color:green;font-weight: bold;">N</span>
        <span style="color:yellow;font-weight: bold;">A</span>
        <span>-</span>
        <span style="color:red;font-weight: bold;">M</span>
        <span style="color:green;font-weight: bold;">A</span>
        <span style="color:blue;font-weight: bold;">E</span>
        <span style="color:yellow;font-weight: bold;">N</span>
        <span style="color:green;font-weight: bold;">D</span>
        <span style="color:blue;font-weight: bold;">E</span>
        <span style="color:red;font-weight: bold;">L</span>
        <span style="color:yellow;font-weight: bold;">E</span>
        <span style="color:red;font-weight: bold;">O</span>
        <span>-</span>
        <span style="color:red;font-weight: bold;">M</span>
        <span style="color:green;font-weight: bold;">T</span>
        <span style="color:red;font-weight: bold;">A</span>
        <span style="color:blue;font-weight: bold;">A</span>
        <span style="color:yellow;font-weight: bold;">N</span>
        <span style="color:green;font-weight: bold;">I</span>
    </p>
<section id="section">
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    {% for advertisement in advertisements %}
    <div class="carousel-item {% if forloop.first %} active {% endif %}">
      <img src="{{ advertisement.advert_img.url }}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ advertisement.title }}</h5>
        <p>{{ advertisement.description }}</p>
      </div>
    </div>
    {% endfor %}
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
  </div>
</div>
</section>


<section class="leader mt-5 mb-5 bg-secondary">
    <h1 class="head-lead" style="color: #16e0bd;text-align: center; text-decoration: underline;">Leaders Section</h1>
    <div class="container leader-section p-5">
        <div class="mp-words d-flex align-items-center mb-5">
            <img class="img-wahesh img-fluid rounded-circle" src="{% static 'images/Theuri.jpg' %}" />
            <div class="name-speech text-end">
                <p><b>"</b> Welcome to Umoja The Great Place to be in the City.Welcome to Umoja The Great Place to be in the CityWelcome to Umoja The Great Place to be in the CityWelcome to Umoja The Great Place to be in the CityWelcome to Umoja The Great Place to be in the City<b>"</b></p>
                <h5 class="d-flex justify-content-end">Goerge Theuri</h5>
            </div>
        </div>
        <hr style="color-tomato;"/>
        <div class="mca-words d-flex mt-5 align-items-center">
            <div class="name-speech text-end">
                <p><b>"</b> Welcome to Umoja The Great Place to be in the City.Welcome to Umoja The Great Place to be in the CityWelcome to Umoja The Great Place to be in the CityWelcome to Umoja The Great Place to be in the CityWelcome to Umoja The Great Place to be in the City<b>"</b></p>
                <h5 class="d-flex justify-content-end">Goerge Theuri</h5>
            </div>
        </div>
    </div>
</section>

<div class="cov-container" style="margin-top: 3%;">
    <div class="covid-container">
        <h4><i>Stay safe.Protect Yourself</i></h4>
        <h4>Mask on,sanitize & wash hands</h4>
        <h6>Check out <a href="{% url 'covid:dashboard' %}" class="covid-butt">Covid19</a> data</h6>
    </div>
</div>



<div class="main-container">
    <h1 class="row-link">News</h1>
    <p><i>We will provide you with the latest news happening in our area</i></p>
    <div class="row">
        {% for update in updates %}
            <div class="news">
                <a href="{% url 'updates:news_details' slug=update.slug %}"><img class="news-img" src="{{ update.news_img.url }}"></a>
                <div class="post-review">
                     <hr>
                    <h6><a class="news-linkkk" href="{% url 'updates:news_details' slug=update.slug %}">{{ update.title }}</a></h6>
                    <p style="color: black;"> {{ update.description|truncatechars:30 }} </p>
                    {% for tag in update.Tags.all %}
                    <span class="tag"> {{ tag }} </span>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <a style="text-align:center" class="buttonlin" href="{% url 'updates:news_list' %}">VIEW MORE NEWS</a>
    </div>
    <hr>

    <h1 class="row-link">Projects</h1>
    <p><i>Here are all the projects done by our local authorities in our area</i></p>
    <div class="row">
        {% for project in projects %}
            <div class="news">
                <a href="{% url 'projectss:project_detail' slug=project.slug %}"><img class="news-img" src="{{ project.proj_img.url }}"></a>
                <hr>
                <div class="post-review">
                    <h6><a class="news-linkkk" href="{% url 'projectss:project_detail' slug=project.slug %}"> {{ project.name }}</a></h6>
                    <p style="color: black;">{{ project.description|truncatechars:30 }}</p>
                </div>
            </div>
        {% endfor %}
        <a style="text-align:center" class="buttonlin" href="{% url 'projectss:project_home'  %}">VIEW MORE PROJECTS</a>
    </div>
    <hr>


    <h1 class="row-link">Vacancies</h1>
    <p><i>View some of the vacant houses in our hood</i></p>
    <div class="row">
        {% for vacancy in vacancies %}
            <div class="vac" >
                <img class="vac-img" src="{{ vacancy.house_img.url }}">
                 <hr>
                <div class="post-review">
                    <h6><a class="news-linkkk" href="{% url 'vacancies:vacancy_detail' slug=vacancy.slug %}">{{ vacancy.location }}</a></h6>
                    <p style="color: black;"> {{ vacancy.description|truncatechars:30 }} </p>
                    <hr>
                    {% for tag in vacancy.tags.all %}
                    <span class="tag"> {{ tag }} </span>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <a style="text-align:center" class="buttonlin" href="{% url 'vacancies:vacancy_home' %}">VIEW MORE VACANCIES</a>
    </div>
    <hr>

    <h1 class="row-link">Culture</h1>
    <p><i>Our culture here in Umoja</i></p>
    <div class="row">
        {% for cultur in culture %}
            <div class="vac">
                <img class="vac-img" src="{{ cultur.img.url }}">
                <hr>
                <div class="post-review">
                    <h6><a class="news-linkkk" href="{% url 'culture:culture_detail' slug=cultur.slug %}" >{{ cultur.name }}</a></h6>
                    <p style="color: black;"> {{ cultur.description|truncatechars:30 }} </p>
                </div>
            </div>
        {% endfor %}
        <a style="text-align:center" class="buttonlin" href="{% url 'culture:culture_home' %}">VIEW MORE</a>
    </div>

    <h1 class="row-link">Facilities</h1>
    <p><i>Here are the facilities of our yard</i></p>
    <div class="row">
        {% for facility in facilities %}
            <div class="vac">
                <img class="vac-img" src="{{ facility.img.url }}">
                <div class="post-review">
                    <h6><a class="news-linkkk" href="{% url 'facilities:facilities_detail' slug=facility.slug %}">{{ facility.name }}</a></h6>
                    <p style="color: black;"> {{ facility.description|truncatechars:30 }}</p>
                    <hr>
                </div>
            </div>
        {% endfor %}
        <a style="text-align:center" class="buttonlin" href="{% url 'facilities:facilities_home' %}">VIEW MORE FACILITIES</a>
    </div>

</div>

<div class="cov-container" style="margin-top: 3%;">
    <div class="covid-container">
        <h4><i>Stay safe.Protect Yourself</i></h4>
        <h4>Mask on,sanitize & wash hands</h4>
        <h6>Check out <a href="{% url 'covid:dashboard' %}" class="covid-butt">Covid19</a> data</h6>
    </div>
</div>

{% endblock %}

updates/templates/updates/navbar.html
<style type="text/css">
    .links-nav{
width: 100%;
height: 100vh;
font-size: 3rem;
text-align: center;
background: #16e0bd;
z-index: 1000;
position: fixed;
display: none;
}



.links-nav ul{list-style: none;padding: 50px;}



.links-nav ul li{
padding: 25px;
}

.navlink{
text-decoration: none ;
color: black;
font-weight: bold;
border: 1px solid transparent;
border-radius: 10px;
padding: 3px 20px;
background: #fff;
}
.navlink:hover{
color: var(--clr-accent);
}
</style>

<nav class="topnav navbar navbar-expand-lg navbar-light bg-warning fixed-top">
        <div class="container">
			<a class="navbar-brand" href="{% url 'updates:homepage' %}"><strong>Umoja</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto d-flex align-items-center">
				<li class="nav-item">
				<a class="nav-link" href="{% url 'updates:news_list' %}">News<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'projectss:project_home' %}">Projects</a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'vacancies:vacancy_home' %}">Vacancies</a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'culture:culture_home' %}">Culture</a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'facilities:facilities_home' %}">Facilities</a>
				</li>
			</ul>
			  <div>
				{% if request.user.is_authenticated %}
				<a href="{% url 'auth_user:logout' %}">Logout</a>
				{% else %}
				<a style="font-weight:bold;text-decoration: underline;" href="{% url 'auth_user:login' %}">Sign In</a>
				<a style="font-weight:bold;" class="btn btn-secondary" href="{% url 'auth_user:register' %}">Sign Up</a>
				{% endif %}
			</div>
          </div>
<!--			<div>-->
<!--				{% if request.user.is_authenticated %}-->
<!--				<a href="{% url 'auth_user:login' %}">Logout</a>-->
<!--				{% else %}-->
<!--				<a style="font-weight:bold;text-decoration: underline;" href="{% url 'auth_user:login' %}">Sign In</a>-->
<!--				<a style="font-weight:bold;" class="btn btn-secondary" href="{% url 'auth_user:register' %}">Sign Up</a>-->
<!--				{% endif %}-->
<!--			</div>-->
        </div>
      </nav>

<!--<nav class="topnav navbar navbar-expand-lg navbar-light bg-warning fixed-top">-->
<!--<div class="container">-->
<!--	<a class="navbar-brand" href="./index.html"><strong>Umoja</strong></a>-->
<!--	<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">-->
<!--	<span class="navbar-toggler-icon"></span>-->
<!--	</button>-->
<!--	<div class="navbar-collapse collapse" id="navbarColor02" style="">-->
<!--		<ul class="navbar-nav mr-auto d-flex align-items-center">-->
<!--			<li class="nav-item">-->
<!--			<a class="nav-link" href="{% url 'updates:news_list' %}">News<span class="sr-only">(current)</span></a>-->
<!--			</li>-->
<!--			<li class="nav-item">-->
<!--			<a class="nav-link" href="{% url 'projectss:project_home' %}">Projects</a>-->
<!--			</li>-->
<!--			<li class="nav-item">-->
<!--			<a class="nav-link" href="{% url 'vacancies:vacancy_home' %}">Vacancies</a>-->
<!--			</li>-->
<!--			<li class="nav-item">-->
<!--			<a class="nav-link" href="{% url 'culture:culture_home' %}">Culture</a>-->
<!--			</li>-->
<!--			<li class="nav-item">-->
<!--			<a class="nav-link" href="{% url 'facilities:facilities_home' %}">Facilities</a>-->
<!--			</li>-->
<!--		</ul>-->

<!--	</div>-->
<!--</div>-->
<!--</nav>-->

<!--<header style="background: #16e0bd;">-->
<!--    <h3 class="logo"><a href="{% url 'updates:homepage' %}"><i>Umoja</i></a></h3>-->
<!--    <div class="menu-login">-->
<!--&lt;!&ndash;        <div class="login-button">&ndash;&gt;-->
<!--&lt;!&ndash;            {% if request.user.is_authenticated %}&ndash;&gt;-->
<!--&lt;!&ndash;            <a class="navli" href="">Logout</a>&ndash;&gt;-->
<!--&lt;!&ndash;            {% else %}&ndash;&gt;-->
<!--&lt;!&ndash;            <a class="navli" href="">Login</a>&ndash;&gt;-->
<!--&lt;!&ndash;            {% endif %}&ndash;&gt;-->
<!--&lt;!&ndash;        </div>&ndash;&gt;-->
<!--        <div class="menu-bar" id="opemen" onclick="openmenu()">-->
<!--            <div class="bar1"></div>-->
<!--            <div class="bar2"></div>-->
<!--            <div class="bar3"></div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="links-nav" id="links-nav">-->
<!--        <p style="font-weight:bold; float: right;margin-right: 10px;cursor: pointer" id="closmen" onclick="closemenu()">X</p>-->
<!--        <ul>-->
<!--            <li><a class="navlink" href="{% url 'updates:news_list' %}">News</a></li>-->
<!--            <li><a class="navlink" href="{% url 'projectss:project_home' %}">Projects</a></li>-->
<!--            <li><a class="navlink" href="{% url 'vacancies:vacancy_home' %}">Vacancies</a></li>-->
<!--            <li><a class="navlink" href="{% url 'culture:culture_home' %}">Culture</a></li>-->
<!--            <li><a class="navlink" href="{% url 'facilities:facilities_home' %}">Facilities</a></li>-->
<!--        </ul>-->
<!--    </div>-->
<!--</header>-->

<!--<script>-->
<!--function openmenu(){-->
<!--    document.getElementById("links-nav").style.display="block";-->
<!--}-->
<!--function closemenu(){-->
<!--    document.getElementById("links-nav").style.display="none";-->
<!--}-->
<!--</script>-->

updates/templates/updates/new_update.html
{% extends "index.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="create-news">
<h1>Edit News</h1>
<form method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <input class="buttonlin" type="submit" value="Update">
</form>
</div>
{% endblock %}

updates/templates/updates/news_create.html
{% extends "index.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="create-news">
<h1> Create News </h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <input class="buttonlin" type="submit" value="Post">
</form>
</div>
{% endblock %}