covid/urls.py
from django.urls import path
from .views import side_bar_data, map_bar_data


app_name='covid'
urlpatterns = [
    path('covid19', side_bar_data, name="dashboard" ),
    path('selectCountry',  map_bar_data, name="graphs" ),
]

culture/urls.py
from django.urls import path
from .views import CultureListView, CultureDetailView, CultureCreateView, UpdateCultureView, DeleteCultureView

app_name='culture'
urlpatterns = [
    path('', CultureListView, name='culture_home'),
    path('create/', CultureCreateView.as_view(), name='create_culture'),
    path('<str:slug>/', CultureDetailView.as_view(), name='culture_detail'),
    path('<str:slug>/update', UpdateCultureView.as_view(), name='update_culture'),
    path('<str:slug>/delete', DeleteCultureView.as_view(), name='delete_culture'),


]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView, UpdateProjectView, DeleteProjectView

app_name='projectss'
urlpatterns = [
    path('', ProjectListView, name='project_home'),
    path('create/', ProjectCreateView.as_view(), name='create_project'),
    path('<str:slug>/', ProjectDetailView.as_view(), name='project_detail'),
    path('<str:slug>/update', UpdateProjectView.as_view(), name='update_project'),
    path('<str:slug>/delete', DeleteProjectView.as_view(), name='delete_project'),


]

umoja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('advert/', include('advertisements.urls')),
    path('projects/', include('projects.urls')),
    path('home/', include('updates.urls')),
    path('culture/', include('culture.urls')),
    path('facilities/', include('facilities.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('covid.urls')),
    path('', include('user_auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

updates/urls.py
from django.urls import path
from .views import DisplayNews, NewsDetails , CreateNews, UpdateNews, DeleteNews, homepage

app_name='updates'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('news/', DisplayNews, name='news_list'),
    path('create/', CreateNews.as_view(), name='news_create'),
    path('<str:slug>/', NewsDetails.as_view(), name='news_details'),
    path('<str:slug>/Update', UpdateNews.as_view(), name='news_update'),
    path('<str:slug>/Delete', DeleteNews.as_view(), name='news_delete'),
]

user_auth/urls.py
from django.urls import path
from .views import LoginView,RegisterView
from django.contrib.auth.views import LogoutView

app_name='auth_user'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page ='auth_user:login'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

covid/views.py
from django.shortcuts import render
import pandas as pd


df3 = pd.read_json('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/world-population-density.json')
def side_bar_data(request):
  cases = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',encoding='utf-8', na_values=None)
  barPlot=cases[['Country/Region',cases.columns[-1]]].groupby('Country/Region').sum()
  barPlot=barPlot.reset_index()
  barPlot.columns = ['Country/Region','values']
  barPlot=barPlot.sort_values(by='values',ascending=False)
  barValues = barPlot['values'].values.tolist()
  countryNames=barPlot['Country/Region'].values.tolist()
  total_cases=cases[cases.columns[-1]].sum()
  dataForMap = mapData(barPlot, countryNames)
  showMap = True

  context ={

    "total_cases": total_cases,
    "countryNames":countryNames,
    "barValues": barValues,
    "dataForMap":dataForMap,
    "showMap": showMap
  }
  return render(request, 'covid/dashboard.html', context)



def mapData(barPlot, countryNames):
  dataForMap =[]
  for i in countryNames:
    try:
      tempdf = df3[df3['name'] ==i]
      temp = {}
      temp['code3']=list(tempdf['code3'].values)[0]
      temp['name'] = i
      temp['value'] = barPlot[barPlot['Country/Region']==i]['values'].sum()
      temp['code']=list(tempdf['code'].values)[0]
      dataForMap.append(temp)
    except:
      pass
  return dataForMap


def map_bar_data(request):
  countryNameSe = request.POST.get('countryName')
  cases = pd.read_csv(
    'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',
    encoding='utf-8', na_values=None)
  barPlot = cases[['Country/Region', cases.columns[-1]]].groupby('Country/Region').sum()
  barPlot = barPlot.reset_index()
  barPlot.columns = ['Country/Region', 'values']
  barPlot = barPlot.sort_values(by='values', ascending=False)
  barValues = barPlot['values'].values.tolist()
  countryNames = barPlot['Country/Region'].values.tolist()
  total_cases = cases[cases.columns[-1]].sum()
  showMap = False


  countryDataSpe = pd.DataFrame(cases[cases['Country/Region']==countryNameSe][cases.columns[4:-1]].sum()).reset_index()
  countryDataSpe.columns=['country','values']
  countryDataSpe['lagVal']=countryDataSpe['values'].shift(1).fillna(0)
  countryDataSpe['incrementVal']=countryDataSpe['values']-countryDataSpe['lagVal']
  countryDataSpe['rollingMean']=countryDataSpe['incrementVal'].rolling(window=4).mean()
  countryDataSpe=countryDataSpe.fillna(0)
  datasetsForLine=countryDataSpe['values'].values.tolist()
  datasetsForLine2={'label':'Rolling Mean 4 days','data':countryDataSpe['rollingMean'].values.tolist()}
  axisvalues = countryDataSpe.index.tolist()

  context = {
    "datasetsForLine2":datasetsForLine2,
    "axisvalues":axisvalues,
    "total_cases": total_cases,
    "countryNames": countryNames,
    "barValues": barValues,
    "showMap" : showMap,
    "datasetsForLine":datasetsForLine,
    "countryNameSe":countryNameSe,

  }
  return render(request, 'covid/dashboard.html', context)

covid/templates/covid/dashboard.html
{% extends "indexcovid.html" %}
{% block content %}


{% load static %}
{% include 'covid/navbar.html' %}
<style>


    .container-cov{
    display: flex;
    justify-content: center;
    }
    .chart{
    width: 40%;
    max-height: 595px;
    overflow : scroll;
    overflow-x: hidden;
    padding: 10px 40px;
    }
    .chart h1{
    text-align: center;
    color: black;
    }
    .map{
    width: 60%;
    }
    .map h2{
    text-align: center;
    }

    .bar-cont{
    margin-top: 3%;
    width: 100%;
    display: flex;
    justify-content: center;
    }


    .bar-cont form{
    width: 30%;
    display: block;
    }
    .but{
    padding : 3px 20px;
    font-size: 10px;
    margin-top: 4px;
    }

    .canva{
    width: 70%;
    float: left;
    }
    .second-container{
    margin-top: 3%;
    padding: 20px 30px;
    }


#container {
    height: 500px;
    min-width: 310px;
    max-width: 800px;
    margin: 0 auto;
}
.loading {
    margin-top: 10em;
    text-align: center;
    color: gray;
}
.covid-container{
width: 70%;
margin: auto;
padding: 40px 40px;
text-align: center;
color: #fff;
}
.covid-container{
background-image: url({% static 'images/corona.gif' %})
}
.covid-container h6{
font-size: 10px;
text-align: right;
padding-right: 35%;
}

.covid-butt{
border: 1px solid transparent;
background-color: crimson;
padding:3px 20px;
font-size: 10px;
color: black;
transition: 0.3s ease in;
cursor: pointer;
}
.covid-butt:hover{
background-color: red;
text-decoration: none;
letter-spacing: 1.5px;
color: #fff;
}
@media(max-width: 600px){
.cov-container{
margin-top: 5%;
}
.covid-container h4{
font-size: 15px;
}
.covid-container h6{
padding: 10px 20px;
}
}


</style>
<div class="container-cov">
    <div class="chart">
        <h3>Total Infections : {{ total_cases }}</h3>
        <div class="bar-cont">
            <form method="post" enctype="multipart/form-data" action="selectCountry">
                {% csrf_token %}
                {% for country in countryNames %}
                <input class="but" type="submit" value="{{ country }}" name="countryName" style="width:100px">
                {% endfor %}
            </form>

            <canvas class="canvas" id="myChart" width="400" height="4050";></canvas>
        </div>
    </div>


    <div class="map">

        <div class="second-container">
            {% if showMap == True %}
            <h2 class="head">World Map</h2>

            <div id="container">
                <div class="loading">
                    <i class="icon-spinner icon-spin icon-large"></i>
                </div>
            </div>
            {% elif showMap == False  %}
            <h2>{{ countryNameSe }}</h2>
            <canvas id="lineChart" width="450";></canvas>
            {% endif %}
        </div>

    </div>

    <div class="cov-container" style="margin-top: 3%;">
</div>
</div>
<div class="covid-container">
        <h4><i>Stay safe.Protect Yourself</i></h4>
        <h4>Mask on,sanitize & wash hands</h4>
<!--        <h6>Check out <a href="{% url 'covid:dashboard' %}" class="covid-butt">Covid19</a> data</h6>-->
    </div>
{% endblock %}

covid/templates/covid/navbar.html
<!--<style>-->
<!--    nav{-->
<!--    font-size: 40px;-->
<!--    height : 80px;-->
<!--    text-align: center;-->
<!--    background: orange;-->
<!--&lt;!&ndash;    background: #16e0bd;&ndash;&gt;-->
<!--    }-->
<!--    nav h1{-->
<!--    text-align: center;-->

<!--    }-->
<!--    .home{-->
<!--    text-align: left;-->
<!--    }-->
<!--    nav h1 a{-->
<!--    text-decoration: none;-->
<!--    color: #fff;-->

<!--    }-->

<!--    nav h1 a:hover{-->
<!--    color: black;-->
<!--    }-->

<!--    @media(max-width: 680px){-->
<!--    nav{-->
<!--    font-size: 30px;-->
<!--    height : 60px;-->
<!--    }-->

<!--    }-->
<!--</style>-->

<!--<nav>-->
<!--    <h1><a href="{% url 'updates:homepage' %}"><i>Umoja</i></a>  <a href="{% url 'covid:dashboard' %}">Covid!9 Update</a></h1>-->
<!--</nav>-->


<nav class="topnav navbar navbar-expand-lg navbar-light bg-warning fixed-top">
        <div class="container">
			<a class="navbar-brand" href="{% url 'updates:homepage' %}"><strong>Umoja</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto d-flex align-items-center">
				<li class="nav-item">
				<a class="nav-link" href="{% url 'updates:news_list' %}">News<span class="sr-only"></span></a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'projectss:project_home' %}">Projects</a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'vacancies:vacancy_home' %}">Vacancies</a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'culture:culture_home' %}">Culture</a>
				</li>
				<li class="nav-item">
				<a class="nav-link" href="{% url 'facilities:facilities_home' %}">Facilities</a>
				</li>
			</ul>
<!--			  <div>-->
<!--				{% if request.user.is_authenticated %}-->
<!--				<a href="{% url 'auth_user:logout' %}">Logout</a>-->
<!--				{% else %}-->
<!--				<a style="font-weight:bold;text-decoration: underline;" href="{% url 'auth_user:login' %}">Sign In</a>-->
<!--				<a style="font-weight:bold;" class="btn btn-secondary" href="{% url 'auth_user:register' %}">Sign Up</a>-->
<!--				{% endif %}-->
<!--			</div>-->
          </div>
<!--			<div>-->
<!--				{% if request.user.is_authenticated %}-->
<!--				<a href="{% url 'auth_user:login' %}">Logout</a>-->
<!--				{% else %}-->
<!--				<a style="font-weight:bold;text-decoration: underline;" href="{% url 'auth_user:login' %}">Sign In</a>-->
<!--				<a style="font-weight:bold;" class="btn btn-secondary" href="{% url 'auth_user:register' %}">Sign Up</a>-->
<!--				{% endif %}-->
<!--			</div>-->
        </div>
      </nav>