covid/urls.py
from django.urls import path
from .views import side_bar_data, map_bar_data


app_name='covid'
urlpatterns = [
    path('covid19', side_bar_data, name="dashboard" ),
    path('selectCountry',  map_bar_data, name="graphs" ),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView, UpdateProjectView, DeleteProjectView

app_name='projectss'
urlpatterns = [
    path('', ProjectListView, name='project_home'),
    path('create/', ProjectCreateView.as_view(), name='create_project'),
    path('<str:slug>/', ProjectDetailView.as_view(), name='project_detail'),
    path('<str:slug>/update', UpdateProjectView.as_view(), name='update_project'),
    path('<str:slug>/delete', DeleteProjectView.as_view(), name='delete_project'),


]

umoja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('advert/', include('advertisements.urls')),
    path('projects/', include('projects.urls')),
    path('home/', include('updates.urls')),
    path('culture/', include('culture.urls')),
    path('facilities/', include('facilities.urls')),
    path('vacancies/', include('vacancies.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('covid.urls')),
    path('', include('user_auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

updates/urls.py
from django.urls import path
from .views import DisplayNews, NewsDetails , CreateNews, UpdateNews, DeleteNews, homepage

app_name='updates'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('news/', DisplayNews, name='news_list'),
    path('create/', CreateNews.as_view(), name='news_create'),
    path('<str:slug>/', NewsDetails.as_view(), name='news_details'),
    path('<str:slug>/Update', UpdateNews.as_view(), name='news_update'),
    path('<str:slug>/Delete', DeleteNews.as_view(), name='news_delete'),
]

projects/models.py
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField


class Projects(models.Model):
    proj_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    proj_img = models.ImageField(upload_to="images",default='images_1.jpg')
    body = RichTextUploadingField()
    project_by = models.CharField(max_length=50)
    date_published = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    slug = models.SlugField(max_length=100, null=True, blank=True)

    class Meta:
        ordering: ['-date_published']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(f'{self.name}{self.proj_id}')
        super(Projects, self).save(*args, **kwargs)

projects/forms.py
from django import forms
from django.forms import ModelForm
from .models import Projects

class CreateProjectForm(forms.ModelForm):
    class Meta:
        model = Projects
        fields = '__all__'

projects/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,DeleteView,CreateView,UpdateView
from .models import Projects
from .forms import CreateProjectForm
from django.urls import reverse_lazy
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .filters import ProjectFilter
from django.contrib.auth.mixins import LoginRequiredMixin

def ProjectListView(request):
    projects = Projects.objects.all().order_by('-date_published')
    myFilter = ProjectFilter(request.GET, queryset=projects)
    projects = myFilter.qs
    page = request.GET.get('page')
    paginator = Paginator(projects, 5)
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_page)


    context = {
        'projects':projects,
        'myFilter':myFilter,
    }
    return render(request, 'projects/project_list.html', context)


class ProjectDetailView(LoginRequiredMixin,DetailView):
    model = Projects
    template_name = 'projects/project_detail.html'
    context_object_name = 'projects'

class ProjectCreateView(CreateView):
    form_class = CreateProjectForm
    template_name = 'projects/create_project.html'
    success_url = reverse_lazy('projectss:project_home')


class UpdateProjectView(UpdateView):
    model = Projects
    fields = '__all__'
    template_name = 'projects/update_project.html'
    success_url = reverse_lazy('projectss:project_home')

class DeleteProjectView(DeleteView):
    model = Projects
    template_name = 'projects/delete_project.html'
    success_url = reverse_lazy('projectss:project_home')

projects/templates/projects/create_project.html
{% extends "index.html" %}
{% block content %}
{% load crispy_forms_tags %}


<div class="create-news" style="margin-top: 2.5%;">
<h1>Create Project</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <input class="buttonlin" type="submit" value="Add Project">
</form>
</div>
{% endblock %}

projects/templates/projects/delete_project.html
{% extends "index.html" %}
{% block content %}



<div class="create-news" style="margin-top: 2.5%;">
<h1>Are you sure you want to delete this project?</h1>
<form method="post">
    {% csrf_token %}
    <input class="buttonlink" type="submit" value="Confirm">
</form>
</div>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends "index.html" %}
{% block content %}





<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pl-2 pt-0 pb-0 bg-white position-relative">
		<div class="h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 pr-6 align-self-center">
					<p class="text-uppercase font-weight-bold">
						<a class="text-danger" href="{% url 'projectss:project_home' %}">Stories</a>
					</p>
					<h1 class="display-4 secondfont mb-3 font-weight-bold">{{ projects.name }}</h1>
					<p class="mb-3">
                        {{ update.description }}
                    </p>
					<div class="d-flex align-items-center">
						<img class="rounded-circle" src="{{ projects.proj_img.url }}" width="70" height="70">
						<small class="ml-2"> <span class="text-muted d-block">{{ projects.date_published }}  Created by:{{ projects.project_by }}</span>
							{% if request.user.is_authenticated %}
							<span><a href="{% url 'projectss:update_project' slug=object.slug %}">Update</a>
    						<a class="text-danger" href="{% url 'projectss:delete_project' slug=object.slug %}">Delete</a></span>
							{% endif %}
						</small>
					</div>
				</div>
				<div class="col-md-6 pr-0">
					<img width="500" height="300" src="{{ projects.proj_img.url }}">
				</div>
			</div>
		</div>
	</div>
</div>

<div class="container pt-4 pb-4">
	<div class="row justify-content-center">
		<div class="col-lg-2 pr-4 mb-4 col-md-12">
			<div class="sticky-top text-center">
				<div class="text-muted">
					Share this
				</div>
			</div>
		</div>
		<div class="col-md-12 col-lg-8">
			<article class="article-post">
			<p>
                {{ projects.body|safe }}
			</p>
			</article>
			<div class="border p-5 bg-lightblue">
				<div class="row justify-content-between">
					<div class="col-md-5 mb-2 mb-md-0">
						<h5 class="font-weight-bold secondfont">Become a member</h5>
						 Get the latest news right in your inbox. We never spam!
					</div>
					<div class="col-md-7">
						<div class="row">
							<div class="col-md-12">
								<input type="text" class="form-control" placeholder="Enter your e-mail address">
							</div>
							<div class="col-md-12 mt-2">
								<button type="submit" class="btn btn-success btn-block">Subscribe</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="cov-container" style="margin-top: 3%;">
    <div class="covid-container">
        <h4><i>Stay safe.Protect Yourself</i></h4>
        <h4>Mask on,sanitize & wash hands</h4>
        <h6>Check out <a href="{% url 'covid:dashboard' %}" class="covid-butt">Covid19</a> data</h6>
    </div>
</div>



{% endblock %}

projects/templates/projects/project_list.html
{% extends "index.html" %}
{% block content %}

{% load static %}
{% load crispy_forms_tags %}
<style>
.post-review h6, p{
    text-align:left;
}
@media(max-width: 600px){
.cov-container{
margin-top: 5%;
}
.covid-container h4{
font-size: 15px;
}
.covid-container h6{
padding: 10px 20px;
}
}

 .carousel-item{
 height:28rem;
 background: #7777;
 position: relative;
 }
 .carousel-item img{
 height: 100%;
 width: 100%;
 object-fit:cover;
 }

 form label{
 display: none;
 }


 form{
 display: flex;
 justify-content: center;
 align-items: center;
 }

 .img-doc, .img-doc img{
 max-height: 180px;
 max-width: 250px;
 object-fit: cover;
 }

</style>

<section class="main-container">
    <div class="mt-5">
        <form method="get">
            {{ myFilter.form|crispy }}
            <input type="submit" class="btn btn-primary ml-3" value="search">
        </form>
    </div>



<div class="container pt-4 pb-4">
    <h1 class="row-link">Projects</h1>
	<div class="row">
        {% for update in projects %}
		<div class="col">
			<div class="card border-0 mb-4 box-shadow h-xl-300 pl-0">
                <div class="img-doc">
                    <img class="img-fluid" height="200"  src="{{ update.proj_img.url }}" />
                </div>
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
					<a class="text-dark" href="{% url 'projectss:project_detail' slug=update.slug %}">{{ update.name|truncatechars:20  }}</a>
					</h2>
					<p class="card-text">
                        {{ update.description|truncatechars:30  }}
                    </p>
					<div>
						<small class="d-block"><a class="text-muted" href="">{{ update.date_created }}</a></small>
					</div>
				</div>
			</div>
		</div>
        {% endfor %}
	</div>
    <div style="margin-top: 5px;">
        {% if projects.has_other_pages %}
        <ul class="pagination">
            {% if projects.has_previous %}
            <li class="page-item"><a href="?page={{ projects.previous_page_number }}" class="page-link">&laquo;</a> </li>
            {% endif %}

            {% for i in projects.paginator.page_range %}
            {% if updates.number == i %}
            <li class="page-item"><a class="active page-link">{{ i }}</a> </li>
            {% else %}
            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a> </li>
            {% endif %}
            {% endfor %}

            {% if projects.has_next %}
            <li class="page-item"><a href="?page={{ projects.next_page_number }}" class="page-link">&raquo;</a></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
    {% if request.user.is_superuser %}
    <a href="{% url 'updates:news_create' %}">New Project</a>
    {% endif %}

</div>



<section id="section" style="margin-top: 3%;">
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    {% for advertisement in advertisements %}
    <div class="carousel-item {% if forloop.first %} active {% endif %}">
      <img src="{{ advertisement.advert_img.url }}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ advertisement.title }}</h5>
        <p>{{ advertisement.description }}</p>
      </div>
    </div>
    {% endfor %}
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
  </div>
</div>
</section>

<div class="cov-container" style="margin-top: 3%;">
    <div class="covid-container">
        <h4><i>Stay safe.Protect Yourself</i></h4>
        <h4>Mask on,sanitize & wash hands</h4>
        <h6>Check out <a href="{% url 'covid:dashboard' %}" class="covid-butt">Covid19</a> data</h6>
    </div>
</div>

</section>
{% endblock %}

projects/templates/projects/update_project.html
{% extends "index.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="create-news">
<h1>Edit Project</h1>
<form method="post">
    {% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <input class="buttonlin" type="submit" value="Update">
</form>
</div>
{% endblock %}